### ISSUE TITLE
Issue while running the code in azure OpenAI

### ISSUE THREAD

**Issue by tanya-kaur** [jimbobbennett/console-gpt#1]
I want to run this repo on azure OpenAI. Please give me steps for the same.

**Comment by jimbobbennett** [comment]
I've copied this to the somatic kernel examples repo, and that has a version (console only, no speech) that can be configured for both OpenAI and Azure OpenAI Service:

https://github.com/jimbobbennett/semantic-kernel-starters/tree/add-sk-console-gpt/sk-csharp-console-chat
